### PR TITLE
Add support for multiple phone numbers

### PR DESCRIPTION
**Pull request by MosheGross**
After having a go at decoding the phonebook.ib file, I suggest a few improvements

1.  Support for Pause (p) and Hash (#) in phone numbers
2. Multiple phone numbers
    According to the backup I was working on, a contact can contain up to 3 numbers
    First one at 0x1E, 2nd at 0x34 and third at 0x4A
3. Phone number types
    The bytes 0x1B, 0x1C & 0x1C determine the types of phone numbers 1 -3 respectively
    where 1 = CELL, 2 = HOME, 3 = WORK

### CODE REVIEW

**Comment by MosheGross** [comment]
@ot2626 What does this do?
`
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /E /Y /R $(ProjectDir)$(OutDir)*.exe $(ProjectDir)App&#xD;&#xA;xcopy /E /Y /R $(ProjectDir)$(OutDir)*.dll $(ProjectDir)App" />
  </Target>
`
Because it's generating a build error, When i remove it, everything works

**Comment by ot2626** [comment]
It's only for convenience. It copies the compiled version into the APP folder.

**Comment by MosheGross** [comment]
It throws an error, can we remove it?

**Comment by ot2626** [comment]
sure np you can remove it.

b.t.w - thank you for your contribution !

**Comment by MosheGross** [comment]
My pleasure. 

Also, I don't mind adding english support, can you point me in the right direction (I don't really do C#, I'm a PHP developer)

**Comment by MosheGross** [comment]
One more thing, can we change *.ib to phonebook.ib in the readme, so Google Search will find it, or do they have different names in different models?

**Pull request merged**
